[workspace]
members = [
    "run_maze",
    "demo",
    "run_tui",
    "maze",
    "monitor",
    "builders",
    "key",
    "tables",
    "solvers",
    "painters",
    "print",
    "speed",
]
resolver = "2"
